name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to ghcr.io
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: seboknt
          password: ${{ secrets.GH_PAT }}

      - name: Build and push for AMD64
        env:
          DOCKER_BUILDKIT: 1
        run: |
          docker buildx create --use
          docker buildx build --platform linux/amd64 --push -t ghcr.io/seboknt/mqtt2db:latest app/mqtt2db/.

      - name: Build and push for ARM64
        env:
          DOCKER_BUILDKIT: 1
        run: |
          docker buildx create --use
          docker buildx build --platform linux/arm64 --push -t ghcr.io/seboknt/mqtt2db:latest app/mqtt2db/.
